import os
os.environ["TOKENIZERS_PARALLELISM"] = 'false'

import json
import gzip
import torch
import random
import argparse
import itertools
import numpy as np
from tqdm import tqdm
from openai import OpenAI
from src.sandbox import Sandbox
from datasets import load_dataset
from collections import defaultdict
from typing import Iterable, Dict, List, Union
from human_eval.data import read_problems, write_jsonl, stream_jsonl
from transformers import AutoTokenizer, AutoModelForCausalLM

class Evaluator(object):
    def __init__(self, model_name_or_path) -> None:
        assert model_name_or_path is not None
        self.model_name_or_path = model_name_or_path
        self.model_short_name = model_name_or_path.split('/')[-1]

    @staticmethod
    def write_jsonl(filename: str, data: Iterable[Dict], append: bool = False):
        if append: mode = 'ab'
        else: mode = 'wb'
        filename = os.path.expanduser(filename)
        if filename.endswith(".gz"):
            with open(filename, mode) as fp:
                with gzip.GzipFile(fileobj=fp, mode='wb') as gzfp:
                    for x in data:
                        gzfp.write((json.dumps(x) + "\n").encode('utf-8'))
        else:
            with open(filename, mode) as fp:
                for x in data:
                    fp.write((json.dumps(x) + "\n").encode('utf-8'))

    @staticmethod
    def estimate_pass_at_k(num_samples: Union[int, List[int], np.ndarray], num_correct: Union[List[int], np.ndarray], k: int):
        def estimator(n: int, c: int, k: int) -> float:
            if n - c < k: return 1.0
            return 1.0 - np.prod(1.0 - k / np.arange(n - c + 1, n + 1))
        if isinstance(num_samples, int):
            num_samples_it = itertools.repeat(num_samples, len(num_correct))
        else:
            assert len(num_samples) == len(num_correct)
            num_samples_it = iter(num_samples)
        return np.array([estimator(int(n), int(c), k) for n, c in zip(num_samples_it, num_correct)])

    def prompt_generate(self, instance):
        content = instance['pretty_content'][0]
        code_prompt = instance['prompt']
        return f"Please solve this problem:\n{content}\n\nCode context:\n{code_prompt}"

    #for starcoder2
    # def generate_completions(self, prompt: str, n_sample=1):
    #     enhanced_prompt = (
    #         "You are a world-class Python programmer. Please output the code solution directly within a Python code block.\n\n"
    #         f"{prompt}"
    #     )

    #     text = (
    #         "Below is an instruction that describes a task. Write a response that appropriately completes the request.\n\n"
    #         "### Instruction:\n"
    #         f"{enhanced_prompt}\n\n"
    #         "### Response:\n"
    #     )

    #     model_inputs = self.tokenizer([text] * n_sample, return_tensors="pt").to("cuda")

    #     stop_tokens = ["<|im_end|>", "<|endoftext|>", "<|im_start|>"]

    #     generate_ids = self.model.generate(
    #         **model_inputs,
    #         max_new_tokens=1024,
    #         do_sample=True,
    #         top_p=0.95,
    #         temperature=0.6,
    #         eos_token_id=self.tokenizer.eos_token_id,
    #         pad_token_id=self.tokenizer.eos_token_id
    #     )

    #     input_length = model_inputs.input_ids.shape[1]
    #     completions = []

    #     for i in range(len(generate_ids)):
    #         new_tokens = generate_ids[i][input_length:]
    #         decoded = self.tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

    #         final_code = decoded
    #         if "```python" in decoded:
    #             try:
    #                 final_code = decoded.split("```python")[1].split("```")[0].strip()
    #             except: pass
    #         elif "```" in decoded:
    #             try:
    #                 final_code = decoded.split("```")[1].split("```")[0].strip()
    #             except: pass

    #         if not hasattr(self, '_first_print_done'):
    #             print(f"\n[Live Check] First code snippet generated by Starcoder2 preview:\n{final_code[:300]}...\n")
    #             self._first_print_done = True

    #         completions.append(final_code)

    #     return completions

    def generate_completions(self, prompt: str, n_sample=1):
        messages = [
            {"role": "system", "content": "You are a world-class Python programmer. Please output the code solution directly within a code block."},
            {"role": "user", "content": prompt}
        ]

        text = self.tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=True)
        model_inputs = self.tokenizer([text] * n_sample, return_tensors="pt").to("cuda")

        stop_tokens = ["<|im_end|>", "<|endoftext|>", "<|im_start|>"]

        generate_ids = self.model.generate(
            **model_inputs,
            max_new_tokens=1024,
            do_sample=True,
            top_p=0.95,
            temperature=0.6,
            eos_token_id=self.tokenizer.eos_token_id,
            pad_token_id=self.tokenizer.eos_token_id
        )

        input_length = model_inputs.input_ids.shape[1]
        completions = []

        for i in range(len(generate_ids)):
            new_tokens = generate_ids[i][input_length:]
            decoded = self.tokenizer.decode(new_tokens, skip_special_tokens=True).strip()

            final_code = decoded
            if "```python" in decoded:
                try:
                    final_code = decoded.split("```python")[1].split("```")[0].strip()
                except: pass
            elif "```" in decoded:
                try:
                    final_code = decoded.split("```")[1].split("```")[0].strip()
                except: pass

            if not hasattr(self, '_first_print_done'):
                print(f"\n[Live Check] First line of code generated by the model preview:\n{final_code[:200]}...\n")
                self._first_print_done = True

            completions.append(final_code)

        return completions

class DistributeWiseEvaluator(Evaluator):
    def __init__(self, model_name_or_path, do_generate, save_name=None) -> None:
        super().__init__(model_name_or_path)
        self.do_generate = do_generate

        self.save_name = save_name if save_name else self.model_short_name
        self.output_dir = "/root/autodl-tmp/SkelDPO/Eval_Results"
        os.makedirs(self.output_dir, exist_ok=True)

        print("Loading dataset Elfsong/Mercury (eval split) from Hugging Face...")
        self.dataset = load_dataset("Elfsong/Mercury", split="eval")

        if self.do_generate:
            print("Loading Model onto Multi-GPUs...")
            self.tokenizer = AutoTokenizer.from_pretrained(
                self.model_name_or_path,
                trust_remote_code=True
            )
            if self.tokenizer.pad_token is None:
                self.tokenizer.pad_token = self.tokenizer.eos_token

            self.model = AutoModelForCausalLM.from_pretrained(
                self.model_name_or_path,
                cache_dir=os.environ.get('HF_HOME'),
                torch_dtype=torch.float16,
                trust_remote_code=True,
                device_map = "auto",
            )

        self.sandbox = Sandbox()

    def generate(self, num_samples_per_task=10):
        samples = defaultdict(list)
        for instance in tqdm(self.dataset.to_list()):
            prompt = self.prompt_generate(instance)

            for completion in self.generate_completions(prompt, num_samples_per_task):
                samples[instance['slug_name']] += [{
                    "task_id": instance['slug_name'],
                    "completion": completion,
                }]

        save_path = os.path.join(self.output_dir, f'{self.save_name}_samples.json')
        with open(save_path, 'w') as sample_f:
            sample_f.write(json.dumps(samples, indent=2))

        print(f"Generation completed! File saved at: {save_path}")
        return samples

    def evaluate(self, num_samples_per_task=1):
        save_path = os.path.join(self.output_dir, f'{self.save_name}_samples.json')
        print(f"Reading generated samples from {save_path}...")
        with open(save_path, 'r') as sample_f:
            samples = json.load(sample_f)

        eval_results = defaultdict(list)
        for instance in tqdm(self.dataset.to_list()):
            slug_name = instance['slug_name']
            if slug_name not in samples: continue

            solutions = samples[slug_name]
            selected_solutions = random.sample(solutions, num_samples_per_task) if num_samples_per_task <= len(solutions) else solutions

            runtimes = list()
            for index, solution in enumerate(instance['solutions']):
                sample = {
                    "solution": solution['solution'],
                    "convert_offline": instance['convert_offline'],
                    "evaluate_offline": instance['evaluate_offline'],
                    "entry_point": instance['entry_point'],
                    "test_cases": json.loads(instance['test_cases']),
                    "solution_index": index,
                    "timeout": 30
                }
                result = self.sandbox.run_sample(sample)
                if result['result'] == "passed":
                    runtimes += [result['runtime']]
            if not runtimes: continue
            runtimes = sorted(runtimes)

            min_runtime = min(runtimes)
            max_runtime = max(runtimes)

            for index, solution in enumerate(selected_solutions):
                sample = {
                    "solution": solution['completion'],
                    "convert_offline": instance['convert_offline'],
                    "evaluate_offline": instance['evaluate_offline'],
                    "entry_point": instance['entry_point'],
                    "test_cases": json.loads(instance['test_cases']),
                    "solution_index": index,
                    "timeout": 30,
                }

                result = self.sandbox.run_sample(sample)

                runtime = result['runtime'] if result['result'] == "passed" else float('inf')
                beyond = max_runtime - runtime
                beyond = min(beyond, 1)
                beyond = max(beyond, 0)
                beyond_precent = beyond / (max_runtime - min_runtime) if max_runtime != min_runtime else 0.0

                eval_results[slug_name] += [{
                    "slug_name": slug_name,
                    "status":  result,
                    "solution": solution['completion'],
                    "runtimes": runtimes,
                    "beyond_p": beyond_precent,
                }]

        eval_path = os.path.join(self.output_dir, f'{self.save_name}_eval.json')
        with open(eval_path, 'w') as sample_f:
            sample_f.write(json.dumps(eval_results, indent=2))
        print(f"Evaluation details saved at: {eval_path}")

        total, passed, beyond = 0, 0, 0
        for slug_name in eval_results:
            cases = eval_results[slug_name]
            total += 1
            beyond += cases[0]['beyond_p']
            if cases[0]['status']['result'] == "passed":
                passed += 1

        if total > 0:
            passed_score = passed / total
            beyond_score = beyond / total
            print("*" * 50)
            print(f"Final Score -> Pass@1: {passed_score:.4f} | Beyond@1: {beyond_score:.4f}")
            print("*" * 50)
        else:
            print("No valid evaluation results.")

        return samples

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description='Mercury Evaluation Framework')
    parser.add_argument('--model_name_or_path', default="/path/to/model", help="Absolute path to your model")
    parser.add_argument('--benchmark', default='DistributeWiseMercury', help="evaluation benchmarks")
    parser.add_argument('--samples', type=int, default=1, help="generation samples per task")
    parser.add_argument('--do_generate', action='store_true', help="run generation")
    parser.add_argument('--do_evaluate', action='store_true', help="run sandbox evaluation")
    parser.add_argument('--save_name', type=str, default=None, help="Custom name for saving output files")

    args = parser.parse_args()

    print(f"Current model: [{args.model_name_or_path}] Benchmark: [{args.benchmark}]")

    evaluator = DistributeWiseEvaluator(args.model_name_or_path, args.do_generate, args.save_name)

    if args.do_generate:
        print(">>> Starting code generation...")
        output = evaluator.generate(num_samples_per_task=args.samples)
    if args.do_evaluate:
        print(">>> Starting sandbox evaluation...")
        output = evaluator.evaluate(num_samples_per_task=args.samples)

    print("Bingo! Full test pipeline completed!")